/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Chicken.gltf -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Attack' | 'Death' | 'Idle' | 'Idle_Peck' | 'Run'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Chicken: THREE.SkinnedMesh
    Body: THREE.Bone
    Root: THREE.Bone
  }
  materials: {
    Atlas: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

type ModelProps = JSX.IntrinsicElements['group'] & {
  currentAction?: string;
}

export function Model({ currentAction = 'Run', ...props }: ModelProps) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('/Chicken.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  React.useEffect(() => {
    // Mapping for this specific model
    let animName = currentAction;
    if (currentAction === 'Jump_Loop') animName = 'Attack'; // Fallback for Happy

    const actionToPlay = actions[animName] || actions['Run'] || actions['Idle'];

    if (actionToPlay) {
      actionToPlay.reset().fadeIn(0.2).play();
      return () => {
        actionToPlay.fadeOut(0.2);
      }
    }
  }, [currentAction, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.Root} />
          <skinnedMesh name="Chicken" geometry={nodes.Chicken.geometry} material={materials.Atlas} skeleton={nodes.Chicken.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Chicken.gltf')
