/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Flowers_1.gltf -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube432: THREE.Mesh
    Cube432_1: THREE.Mesh
    Cube432_2: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    Atlas: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Flowers_1.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube432.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube432_1.geometry} material={materials['Material.020']} />
      <mesh geometry={nodes.Cube432_2.geometry} material={materials.Atlas} />
    </group>
  )
}

useGLTF.preload('/Flowers_1.gltf')
